server:
  host: xendit-account-service
  port: 8080
  url: https://xendit-account-service
  cors:
    allowedOrigins:
    - '*'
    allowedHeaders:
    - Content-Type
    - Sec-Fetch-Dest
    - Referer
    - accept
    - User-Agent
    allowedMethods:
    - POST
    - GET
    - OPTIONS
    - HEAD

log:
  level: "debug"

db:
  host: postgres
  port: 5432
  username: xendit
  password: xendit
  name: xendit
  pool:
    minOpen: 10
    maxOpen: 100
  migrate: true
  logMode: true
